-- GENERATED by scripts/gen-seed.mjs. Do not edit by hand.
-- reset_demo(): restores Glow Salon's seeded day. Called by the Reset demo button.
-- Static history (90 days of bookings, area_signals, benchmarks, funder offers) is in 0003.

create or replace function rebuild_slots(p_merchant text, p_date date)
returns void language plpgsql security definer set search_path = public as $$
declare
  open_at timestamptz;
  close_at timestamptz;
begin
  select (p_date + m.opens_at) at time zone 'Asia/Kolkata', (p_date + m.closes_at) at time zone 'Asia/Kolkata'
    into open_at, close_at from merchants m where m.id = p_merchant;

  delete from slots where merchant_id = p_merchant
    and start_at >= open_at and start_at < close_at;

  -- Gaps between bookings on each chair, including before the first and after the last.
  insert into slots (merchant_id, chair, start_at, end_at, state)
  select p_merchant, chair, gap_start, gap_end, 'free'
  from (
    select c.chair,
           coalesce(lag(b.end_at) over w, open_at) as gap_start,
           b.start_at as gap_end
    from generate_series(1, 6) as c(chair)
    left join lateral (
      select start_at, end_at from bookings
      where merchant_id = p_merchant and chair = c.chair and start_at >= open_at and start_at < close_at
      union all select close_at, close_at
    ) b on true
    window w as (partition by c.chair order by b.start_at)
  ) g
  where gap_end - gap_start >= interval '20 minutes';
end $$;

create or replace function reset_demo()
returns void language plpgsql security definer set search_path = public as $$
declare
  d date := '2026-10-13';
begin
  delete from payments;
  delete from offers;
  delete from events where merchant_id = 'glow';
  delete from slots where merchant_id = 'glow';
  delete from demo_state where merchant_id = 'glow';
  delete from bookings where merchant_id = 'glow' and start_at >= (d::timestamp at time zone 'Asia/Kolkata');

  insert into merchants (id, name, owner_name, city, area_id, stylists, opens_at, closes_at, max_discount,
    allowed_offers, never_discount_services, vip_customer_ids, daily_message_cap, quiet_hours_start,
    quiet_hours_end, approval_mode, front_desk_name, front_desk_phone, logo_url)
  values ('glow', 'Glow Salon', 'Priya', 'Hyderabad', 'hyd-madhapur',
    array['Anjali','Ravi','Meena','Farhan','Lakshmi','Arjun'], '10:00', '20:00', 200,
    array['pay_now','friend','pass'], array['svc_colour'], array['c_anjali_v','c_raj','c_sunita'], 60, '21:00', '09:00',
    'ask_first', 'Sneha', '+91 98480 55555', '/glow-logo.svg')
  on conflict (id) do update set name = excluded.name, owner_name = excluded.owner_name, city = excluded.city,
    area_id = excluded.area_id, stylists = excluded.stylists, opens_at = excluded.opens_at,
    closes_at = excluded.closes_at, max_discount = excluded.max_discount, allowed_offers = excluded.allowed_offers,
    never_discount_services = excluded.never_discount_services, vip_customer_ids = excluded.vip_customer_ids,
    daily_message_cap = excluded.daily_message_cap, quiet_hours_start = excluded.quiet_hours_start,
    quiet_hours_end = excluded.quiet_hours_end, approval_mode = excluded.approval_mode,
    front_desk_name = excluded.front_desk_name, front_desk_phone = excluded.front_desk_phone,
    logo_url = excluded.logo_url;

  insert into services (id, merchant_id, name, duration_min, price, floor_price, discountable) values
    ('svc_haircut','glow','Haircut',45,450,350,true),
    ('svc_spa','glow','Hair spa',60,1200,950,true),
    ('svc_beard','glow','Beard trim',20,200,150,true),
    ('svc_colour','glow','Colour',90,2500,null,false)
  on conflict (id) do update set name = excluded.name, duration_min = excluded.duration_min, price = excluded.price,
    floor_price = excluded.floor_price, discountable = excluded.discountable;

  insert into customers (id, merchant_id, name, phone, distance_km, last_visit_at, usual_gap_days, usual_time_band,
    usual_service_id, avg_spend, past_offer_response, card_issuer, is_regular, opted_out) values
    ('c_riya','glow','Riya Reddy','+91 98480 10000',1.2,('2026-10-13 12:00+05:30'::timestamptz - interval '42 days'),35,'afternoon','svc_haircut',520,0.6,'HDFC',false,false),
    ('c_aditya','glow','Aditya Rao','+91 98480 10137',0.8,('2026-10-13 12:00+05:30'::timestamptz - interval '38 days'),30,'afternoon','svc_haircut',480,0.5,'ICICI',false,false),
    ('c_sneha_k','glow','Sneha Kulkarni','+91 98480 10274',2.1,('2026-10-13 12:00+05:30'::timestamptz - interval '50 days'),42,'afternoon','svc_spa',1250,0.45,'HDFC',false,false),
    ('c_imran','glow','Imran Shaikh','+91 98480 10411',1.5,('2026-10-13 12:00+05:30'::timestamptz - interval '27 days'),21,'afternoon','svc_beard',260,0.55,null,false,false),
    ('c_pooja','glow','Pooja Menon','+91 98480 10548',3,('2026-10-13 12:00+05:30'::timestamptz - interval '47 days'),40,'afternoon','svc_haircut',470,0.4,'SBI',false,false),
    ('c_karthik','glow','Karthik Varma','+91 98480 10685',1.9,('2026-10-13 12:00+05:30'::timestamptz - interval '33 days'),28,'afternoon','svc_haircut',450,0.35,'HDFC',false,false),
    ('c_nisha','glow','Nisha Agarwal','+91 98480 10822',2.6,('2026-10-13 12:00+05:30'::timestamptz - interval '64 days'),56,'afternoon','svc_spa',1180,0.5,'Axis',false,false),
    ('c_rahul','glow','Rahul Desai','+91 98480 10959',0.6,('2026-10-13 12:00+05:30'::timestamptz - interval '30 days'),25,'evening','svc_haircut',450,0.3,'Kotak',false,false),
    ('c_divya','glow','Divya Nair','+91 98480 11096',3.8,('2026-10-13 12:00+05:30'::timestamptz - interval '45 days'),35,'afternoon','svc_haircut',500,0.45,'HDFC',false,false),
    ('c_sameer','glow','Sameer Khan','+91 98480 11233',1.1,('2026-10-13 12:00+05:30'::timestamptz - interval '24 days'),21,'afternoon','svc_beard',220,0.4,'ICICI',false,false),
    ('c_ananya','glow','Ananya Bose','+91 98480 11370',4.4,('2026-10-13 12:00+05:30'::timestamptz - interval '52 days'),45,'afternoon','svc_spa',1300,0.35,null,false,false),
    ('c_vikram','glow','Vikram Singh','+91 98480 11507',2.3,('2026-10-13 12:00+05:30'::timestamptz - interval '36 days'),30,'morning','svc_haircut',450,0.3,'SBI',false,false),
    ('c_meera','glow','Meera Joshi','+91 98480 11644',5.2,('2026-10-13 12:00+05:30'::timestamptz - interval '41 days'),35,'afternoon','svc_haircut',480,0.25,'HDFC',false,false),
    ('c_arun','glow','Arun Pillai','+91 98480 11781',1.7,('2026-10-13 12:00+05:30'::timestamptz - interval '29 days'),24,'evening','svc_beard',200,0.2,null,false,false),
    ('c_tanvi','glow','Tanvi Shah','+91 98480 11918',6.1,('2026-10-13 12:00+05:30'::timestamptz - interval '49 days'),42,'afternoon','svc_haircut',460,0.3,'Axis',false,false),
    ('c_harsh','glow','Harsh Gupta','+91 98480 12055',2.8,('2026-10-13 12:00+05:30'::timestamptz - interval '34 days'),28,'morning','svc_haircut',450,0.15,'ICICI',false,false),
    ('c_kavya','glow','Kavya Iyer','+91 98480 12192',2.4,('2026-10-13 12:00+05:30'::timestamptz - interval '70 days'),30,'afternoon','svc_haircut',450,0.2,'HDFC',false,false),
    ('c_rohit','glow','Rohit Malhotra','+91 98480 12329',3.3,('2026-10-13 12:00+05:30'::timestamptz - interval '95 days'),35,'afternoon','svc_haircut',450,0.1,'SBI',false,false),
    ('c_shalini','glow','Shalini Rao','+91 98480 12466',4,('2026-10-13 12:00+05:30'::timestamptz - interval '120 days'),45,'afternoon','svc_spa',1200,0.1,null,false,false),
    ('c_naveen','glow','Naveen Kumar','+91 98480 12603',1.4,('2026-10-13 12:00+05:30'::timestamptz - interval '88 days'),30,'evening','svc_haircut',450,0.15,'Kotak',false,false),
    ('c_preeti','glow','Preeti Saxena','+91 98480 12740',2.9,('2026-10-13 12:00+05:30'::timestamptz - interval '140 days'),50,'afternoon','svc_haircut',470,0.05,'HDFC',false,false),
    ('c_sanjay','glow','Sanjay Patil','+91 98480 12877',5.5,('2026-10-13 12:00+05:30'::timestamptz - interval '110 days'),40,'morning','svc_beard',200,0.1,null,false,false),
    ('c_lavanya','glow','Lavanya Krishnan','+91 98480 13014',3.6,('2026-10-13 12:00+05:30'::timestamptz - interval '100 days'),42,'afternoon','svc_spa',1150,0.1,'ICICI',false,false),
    ('c_deepak','glow','Deepak Choudhary','+91 98480 13151',2.2,('2026-10-13 12:00+05:30'::timestamptz - interval '92 days'),28,'evening','svc_haircut',450,0.1,'Axis',false,false),
    ('c_priyanka','glow','Priyanka Das','+91 98480 13288',1,('2026-10-13 12:00+05:30'::timestamptz - interval '18 days'),21,'morning','svc_haircut',450,0,'HDFC',true,false),
    ('c_manoj','glow','Manoj Tiwari','+91 98480 13425',0.9,('2026-10-13 12:00+05:30'::timestamptz - interval '22 days'),21,'evening','svc_beard',200,0,null,true,false),
    ('c_swati','glow','Swati Bhat','+91 98480 13562',1.6,('2026-10-13 12:00+05:30'::timestamptz - interval '25 days'),28,'morning','svc_spa',1200,0,'ICICI',true,false),
    ('c_gautam','glow','Gautam Sen','+91 98480 13699',2,('2026-10-13 12:00+05:30'::timestamptz - interval '20 days'),21,'evening','svc_haircut',450,0,'SBI',true,false),
    ('c_ritu','glow','Ritu Arora','+91 98480 13836',1.3,('2026-10-13 12:00+05:30'::timestamptz - interval '30 days'),28,'morning','svc_haircut',480,0.05,'HDFC',true,false),
    ('c_nikhil','glow','Nikhil Jain','+91 98480 13973',0.7,('2026-10-13 12:00+05:30'::timestamptz - interval '14 days'),14,'evening','svc_beard',200,0,'Kotak',true,false),
    ('c_bhavana','glow','Bhavana Reddy','+91 98480 14110',2.5,('2026-10-13 12:00+05:30'::timestamptz - interval '26 days'),28,'morning','svc_spa',1250,0,'Axis',true,false),
    ('c_suresh','glow','Suresh Naidu','+91 98480 14247',1.8,('2026-10-13 12:00+05:30'::timestamptz - interval '21 days'),21,'evening','svc_haircut',450,0,null,true,false),
    ('c_aparna','glow','Aparna Ghosh','+91 98480 14384',3.1,('2026-10-13 12:00+05:30'::timestamptz - interval '29 days'),30,'morning','svc_haircut',460,0,'HDFC',true,false),
    ('c_varun','glow','Varun Kapoor','+91 98480 14521',1.2,('2026-10-13 12:00+05:30'::timestamptz - interval '16 days'),14,'evening','svc_beard',220,0,'ICICI',true,false),
    ('c_keerthi','glow','Keerthi Prasad','+91 98480 14658',2.7,('2026-10-13 12:00+05:30'::timestamptz - interval '24 days'),28,'morning','svc_haircut',450,0,'SBI',true,false),
    ('c_farah','glow','Farah Siddiqui','+91 98480 14795',1.9,('2026-10-13 12:00+05:30'::timestamptz - interval '31 days'),35,'evening','svc_spa',1200,0.05,null,true,false),
    ('c_ajay','glow','Ajay Yadav','+91 98480 14932',0.5,('2026-10-13 12:00+05:30'::timestamptz - interval '12 days'),14,'morning','svc_beard',200,0,'Axis',true,false),
    ('c_madhu','glow','Madhuri Rao','+91 98480 15069',2.2,('2026-10-13 12:00+05:30'::timestamptz - interval '27 days'),28,'evening','svc_haircut',450,0,'HDFC',true,false),
    ('c_anjali_v','glow','Anjali Verma','+91 98480 15206',1.5,('2026-10-13 12:00+05:30'::timestamptz - interval '20 days'),21,'morning','svc_colour',3200,0,'HDFC',true,false),
    ('c_raj','glow','Raj Malhotra','+91 98480 15343',2.8,('2026-10-13 12:00+05:30'::timestamptz - interval '15 days'),14,'evening','svc_spa',2400,0,'ICICI',true,false),
    ('c_sunita','glow','Sunita Reddy','+91 98480 15480',3.4,('2026-10-13 12:00+05:30'::timestamptz - interval '25 days'),28,'morning','svc_colour',2900,0,'Kotak',true,false),
    ('c_rakesh','glow','Rakesh Sharma','+91 98480 15617',1.1,('2026-10-13 12:00+05:30'::timestamptz - interval '40 days'),30,'afternoon','svc_haircut',450,0,'SBI',false,true),
    ('c_neha','glow','Neha Chopra','+91 98480 15754',2,('2026-10-13 12:00+05:30'::timestamptz - interval '45 days'),35,'afternoon','svc_spa',1200,0,'HDFC',false,true),
    ('c_abhishek','glow','Abhishek Roy','+91 98480 15891',0.9,('2026-10-13 12:00+05:30'::timestamptz - interval '33 days'),28,'afternoon','svc_beard',200,0,null,false,true),
    ('c_sowmya','glow','Sowmya Iyer','+91 98480 16028',12.5,('2026-10-13 12:00+05:30'::timestamptz - interval '44 days'),35,'afternoon','svc_haircut',450,0.2,'HDFC',false,false),
    ('c_prakash','glow','Prakash Reddy','+91 98480 16165',9.8,('2026-10-13 12:00+05:30'::timestamptz - interval '39 days'),30,'afternoon','svc_haircut',450,0.15,'ICICI',false,false),
    ('c_jyothi','glow','Jyothi Rani','+91 98480 16302',14.2,('2026-10-13 12:00+05:30'::timestamptz - interval '60 days'),45,'afternoon','svc_spa',1200,0.1,null,false,false),
    ('c_kiran','glow','Kiran Babu','+91 98480 16439',11,('2026-10-13 12:00+05:30'::timestamptz - interval '35 days'),28,'evening','svc_beard',200,0.1,'SBI',false,false),
    ('c_mohan','glow','Mohan Lal','+91 98480 16576',15,('2026-10-13 12:00+05:30'::timestamptz - interval '50 days'),40,'afternoon','svc_haircut',450,0.05,'Axis',false,false),
    ('c_geeta','glow','Geeta Murthy','+91 98480 16713',8.7,('2026-10-13 12:00+05:30'::timestamptz - interval '48 days'),42,'afternoon','svc_haircut',470,0.2,'HDFC',false,false),
    ('c_arjun_m','glow','Arjun Mehta','+91 98480 16850',1.4,('2026-10-13 12:00+05:30'::timestamptz - interval '6 days'),28,'afternoon','svc_haircut',450,0.4,'HDFC',false,false),
    ('c_simran','glow','Simran Kaur','+91 98480 16987',2.2,('2026-10-13 12:00+05:30'::timestamptz - interval '9 days'),35,'afternoon','svc_spa',1200,0.35,'ICICI',false,false),
    ('c_vivek','glow','Vivek Anand','+91 98480 17124',0.8,('2026-10-13 12:00+05:30'::timestamptz - interval '4 days'),21,'evening','svc_beard',200,0.3,null,false,false),
    ('c_shreya','glow','Shreya Ghoshal','+91 98480 17261',3.5,('2026-10-13 12:00+05:30'::timestamptz - interval '11 days'),42,'afternoon','svc_haircut',480,0.3,'SBI',false,false),
    ('c_amit','glow','Amit Trivedi','+91 98480 17398',1.6,('2026-10-13 12:00+05:30'::timestamptz - interval '8 days'),30,'afternoon','svc_haircut',450,0.25,'Kotak',false,false),
    ('c_lakshmi_p','glow','Lakshmi Priya','+91 98480 17535',2.9,('2026-10-13 12:00+05:30'::timestamptz - interval '13 days'),45,'afternoon','svc_spa',1150,0.3,'HDFC',false,false),
    ('c_yash','glow','Yash Bhatia','+91 98480 17672',1,('2026-10-13 12:00+05:30'::timestamptz - interval '5 days'),21,'evening','svc_beard',200,0.2,'Axis',false,false),
    ('c_isha','glow','Isha Kapoor','+91 98480 17809',4.1,('2026-10-13 12:00+05:30'::timestamptz - interval '10 days'),35,'afternoon','svc_haircut',460,0.3,null,false,false),
    ('c_rohan','glow','Rohan Verghese','+91 98480 17946',2.4,('2026-10-13 12:00+05:30'::timestamptz - interval '7 days'),28,'morning','svc_haircut',450,0.2,'ICICI',false,false),
    ('c_pallavi','glow','Pallavi Sinha','+91 98480 18083',3,('2026-10-13 12:00+05:30'::timestamptz - interval '12 days'),30,'afternoon','svc_haircut',450,0.25,'HDFC',false,false)
  on conflict (id) do update set name = excluded.name, phone = excluded.phone, distance_km = excluded.distance_km,
    last_visit_at = excluded.last_visit_at, usual_gap_days = excluded.usual_gap_days,
    usual_time_band = excluded.usual_time_band, usual_service_id = excluded.usual_service_id,
    avg_spend = excluded.avg_spend, past_offer_response = excluded.past_offer_response,
    card_issuer = excluded.card_issuer, is_regular = excluded.is_regular, opted_out = excluded.opted_out;

  insert into bookings (merchant_id, customer_id, guest_name, service_id, chair, start_at, end_at, price, source) values
    ('glow','c_anjali_v',null,'svc_spa',1,'2026-10-13 10:00+05:30','2026-10-13 11:00+05:30',1200,'crm'),
    ('glow','c_bhavana',null,'svc_haircut',1,'2026-10-13 11:15+05:30','2026-10-13 12:00+05:30',450,'crm'),
    ('glow','c_gautam',null,'svc_spa',1,'2026-10-13 12:00+05:30','2026-10-13 13:00+05:30',1200,'crm'),
    ('glow','c_varun',null,'svc_haircut',1,'2026-10-13 17:00+05:30','2026-10-13 17:45+05:30',450,'crm'),
    ('glow','c_prakash',null,'svc_spa',1,'2026-10-13 17:55+05:30','2026-10-13 18:55+05:30',1200,'crm'),
    ('glow','c_yash',null,'svc_beard',1,'2026-10-13 18:55+05:30','2026-10-13 19:15+05:30',200,'crm'),
    ('glow','c_suresh',null,'svc_spa',2,'2026-10-13 10:00+05:30','2026-10-13 11:00+05:30',1200,'crm'),
    ('glow','c_shreya',null,'svc_haircut',2,'2026-10-13 11:30+05:30','2026-10-13 12:15+05:30',450,'crm'),
    ('glow','c_mohan',null,'svc_beard',2,'2026-10-13 12:25+05:30','2026-10-13 12:45+05:30',200,'crm'),
    ('glow','c_sunita',null,'svc_beard',2,'2026-10-13 16:30+05:30','2026-10-13 16:50+05:30',200,'crm'),
    ('glow','c_swati',null,'svc_spa',2,'2026-10-13 17:00+05:30','2026-10-13 18:00+05:30',1200,'crm'),
    ('glow','c_sowmya',null,'svc_spa',2,'2026-10-13 18:00+05:30','2026-10-13 19:00+05:30',1200,'crm'),
    ('glow','c_rohan',null,'svc_spa',2,'2026-10-13 19:00+05:30','2026-10-13 20:00+05:30',1200,'crm'),
    ('glow','c_nikhil',null,'svc_spa',3,'2026-10-13 10:45+05:30','2026-10-13 11:45+05:30',1200,'crm'),
    ('glow','c_raj',null,'svc_haircut',3,'2026-10-13 11:45+05:30','2026-10-13 12:30+05:30',450,'crm'),
    ('glow','c_manoj',null,'svc_beard',3,'2026-10-13 12:30+05:30','2026-10-13 12:50+05:30',200,'crm'),
    ('glow','c_ritu',null,'svc_beard',3,'2026-10-13 12:50+05:30','2026-10-13 13:10+05:30',200,'crm'),
    ('glow','c_arjun_m',null,'svc_beard',3,'2026-10-13 13:10+05:30','2026-10-13 13:30+05:30',200,'crm'),
    ('glow','c_simran',null,'svc_haircut',3,'2026-10-13 17:30+05:30','2026-10-13 18:15+05:30',450,'crm'),
    ('glow','c_aparna',null,'svc_spa',3,'2026-10-13 18:15+05:30','2026-10-13 19:15+05:30',1200,'crm'),
    ('glow','c_geeta',null,'svc_haircut',3,'2026-10-13 19:15+05:30','2026-10-13 20:00+05:30',450,'crm'),
    ('glow','c_lakshmi_p',null,'svc_haircut',4,'2026-10-13 10:00+05:30','2026-10-13 10:45+05:30',450,'crm'),
    ('glow','c_ajay',null,'svc_beard',4,'2026-10-13 10:55+05:30','2026-10-13 11:15+05:30',200,'crm'),
    ('glow','c_kiran',null,'svc_colour',4,'2026-10-13 11:45+05:30','2026-10-13 13:15+05:30',2500,'crm'),
    ('glow','c_madhu',null,'svc_beard',4,'2026-10-13 13:20+05:30','2026-10-13 13:40+05:30',200,'crm'),
    ('glow','c_isha',null,'svc_beard',4,'2026-10-13 13:40+05:30','2026-10-13 14:00+05:30',200,'crm'),
    ('glow','c_vivek',null,'svc_haircut',4,'2026-10-13 17:00+05:30','2026-10-13 17:45+05:30',450,'crm'),
    ('glow','c_pallavi',null,'svc_haircut',4,'2026-10-13 17:45+05:30','2026-10-13 18:30+05:30',450,'crm'),
    ('glow','c_farah',null,'svc_haircut',4,'2026-10-13 19:15+05:30','2026-10-13 20:00+05:30',450,'crm'),
    ('glow','c_jyothi',null,'svc_haircut',5,'2026-10-13 10:00+05:30','2026-10-13 10:45+05:30',450,'crm'),
    ('glow','c_priyanka',null,'svc_haircut',5,'2026-10-13 11:00+05:30','2026-10-13 11:45+05:30',450,'crm'),
    ('glow','c_amit',null,'svc_haircut',5,'2026-10-13 11:45+05:30','2026-10-13 12:30+05:30',450,'crm'),
    ('glow','c_keerthi',null,'svc_beard',5,'2026-10-13 17:00+05:30','2026-10-13 17:20+05:30',200,'crm'),
    ('glow',null,'Sana Mirza','svc_haircut',5,'2026-10-13 17:30+05:30','2026-10-13 18:15+05:30',450,'crm'),
    ('glow',null,'Kunal Bajaj','svc_spa',5,'2026-10-13 18:15+05:30','2026-10-13 19:15+05:30',1200,'crm'),
    ('glow',null,'Ishaan Reddy','svc_haircut',5,'2026-10-13 19:15+05:30','2026-10-13 20:00+05:30',450,'crm'),
    ('glow',null,'Neelima Rao','svc_spa',6,'2026-10-13 10:30+05:30','2026-10-13 11:30+05:30',1200,'crm'),
    ('glow',null,'Tarun Goud','svc_colour',6,'2026-10-13 11:35+05:30','2026-10-13 13:05+05:30',2500,'crm'),
    ('glow',null,'Fatima Begum','svc_beard',6,'2026-10-13 13:05+05:30','2026-10-13 13:25+05:30',200,'crm'),
    ('glow',null,'Chaitanya K','svc_haircut',6,'2026-10-13 13:25+05:30','2026-10-13 14:10+05:30',450,'crm'),
    ('glow',null,'Revathi S','svc_beard',6,'2026-10-13 14:10+05:30','2026-10-13 14:30+05:30',200,'crm'),
    ('glow',null,'Pavan Kalyan','svc_spa',6,'2026-10-13 18:00+05:30','2026-10-13 19:00+05:30',1200,'crm'),
    ('glow',null,'Hema Latha','svc_spa',6,'2026-10-13 19:00+05:30','2026-10-13 20:00+05:30',1200,'crm'),
    ('glow','c_aparna',null,'svc_haircut',1,'2026-10-14 10:00+05:30','2026-10-14 10:45+05:30',450,'crm'),
    ('glow','c_ritu',null,'svc_haircut',1,'2026-10-14 10:45+05:30','2026-10-14 11:30+05:30',450,'crm'),
    ('glow','c_prakash',null,'svc_haircut',1,'2026-10-14 11:30+05:30','2026-10-14 12:15+05:30',450,'crm'),
    ('glow','c_rohan',null,'svc_spa',1,'2026-10-14 12:15+05:30','2026-10-14 13:15+05:30',1200,'crm'),
    ('glow','c_farah',null,'svc_haircut',1,'2026-10-14 13:15+05:30','2026-10-14 14:00+05:30',450,'crm'),
    ('glow','c_kiran',null,'svc_spa',1,'2026-10-14 16:00+05:30','2026-10-14 17:00+05:30',1200,'crm'),
    ('glow','c_isha',null,'svc_haircut',1,'2026-10-14 17:05+05:30','2026-10-14 17:50+05:30',450,'crm'),
    ('glow','c_sunita',null,'svc_beard',1,'2026-10-14 17:50+05:30','2026-10-14 18:10+05:30',200,'crm'),
    ('glow','c_swati',null,'svc_haircut',1,'2026-10-14 18:10+05:30','2026-10-14 18:55+05:30',450,'crm'),
    ('glow','c_manoj',null,'svc_beard',1,'2026-10-14 18:55+05:30','2026-10-14 19:15+05:30',200,'crm'),
    ('glow','c_arjun_m',null,'svc_haircut',1,'2026-10-14 19:15+05:30','2026-10-14 20:00+05:30',450,'crm'),
    ('glow','c_raj',null,'svc_haircut',2,'2026-10-14 10:00+05:30','2026-10-14 10:45+05:30',450,'crm'),
    ('glow','c_varun',null,'svc_spa',2,'2026-10-14 10:50+05:30','2026-10-14 11:50+05:30',1200,'crm'),
    ('glow','c_mohan',null,'svc_beard',2,'2026-10-14 11:50+05:30','2026-10-14 12:10+05:30',200,'crm'),
    ('glow','c_gautam',null,'svc_beard',2,'2026-10-14 12:10+05:30','2026-10-14 12:30+05:30',200,'crm'),
    ('glow','c_lakshmi_p',null,'svc_haircut',2,'2026-10-14 12:30+05:30','2026-10-14 13:15+05:30',450,'crm'),
    ('glow','c_nikhil',null,'svc_haircut',2,'2026-10-14 13:15+05:30','2026-10-14 14:00+05:30',450,'crm'),
    ('glow','c_ajay',null,'svc_haircut',2,'2026-10-14 14:00+05:30','2026-10-14 14:45+05:30',450,'crm'),
    ('glow','c_priyanka',null,'svc_haircut',2,'2026-10-14 14:45+05:30','2026-10-14 15:30+05:30',450,'crm'),
    ('glow','c_suresh',null,'svc_spa',2,'2026-10-14 17:00+05:30','2026-10-14 18:00+05:30',1200,'crm'),
    ('glow','c_simran',null,'svc_haircut',2,'2026-10-14 18:10+05:30','2026-10-14 18:55+05:30',450,'crm'),
    ('glow','c_yash',null,'svc_haircut',2,'2026-10-14 18:55+05:30','2026-10-14 19:40+05:30',450,'crm'),
    ('glow','c_sowmya',null,'svc_beard',2,'2026-10-14 19:40+05:30','2026-10-14 20:00+05:30',200,'crm'),
    ('glow','c_geeta',null,'svc_haircut',3,'2026-10-14 10:00+05:30','2026-10-14 10:45+05:30',450,'crm'),
    ('glow','c_keerthi',null,'svc_colour',3,'2026-10-14 10:50+05:30','2026-10-14 12:20+05:30',2500,'crm'),
    ('glow','c_vivek',null,'svc_beard',3,'2026-10-14 12:20+05:30','2026-10-14 12:40+05:30',200,'crm'),
    ('glow','c_jyothi',null,'svc_beard',3,'2026-10-14 12:40+05:30','2026-10-14 13:00+05:30',200,'crm'),
    ('glow','c_bhavana',null,'svc_haircut',3,'2026-10-14 14:30+05:30','2026-10-14 15:15+05:30',450,'crm'),
    ('glow','c_anjali_v',null,'svc_haircut',3,'2026-10-14 15:25+05:30','2026-10-14 16:10+05:30',450,'crm'),
    ('glow','c_pallavi',null,'svc_beard',3,'2026-10-14 16:10+05:30','2026-10-14 16:30+05:30',200,'crm'),
    ('glow','c_amit',null,'svc_spa',3,'2026-10-14 16:30+05:30','2026-10-14 17:30+05:30',1200,'crm'),
    ('glow','c_shreya',null,'svc_spa',3,'2026-10-14 17:30+05:30','2026-10-14 18:30+05:30',1200,'crm'),
    ('glow','c_madhu',null,'svc_haircut',3,'2026-10-14 18:30+05:30','2026-10-14 19:15+05:30',450,'crm'),
    ('glow',null,'Sana Mirza','svc_haircut',3,'2026-10-14 19:15+05:30','2026-10-14 20:00+05:30',450,'crm'),
    ('glow',null,'Kunal Bajaj','svc_spa',4,'2026-10-14 10:00+05:30','2026-10-14 11:00+05:30',1200,'crm'),
    ('glow',null,'Ishaan Reddy','svc_spa',4,'2026-10-14 11:10+05:30','2026-10-14 12:10+05:30',1200,'crm'),
    ('glow',null,'Neelima Rao','svc_haircut',4,'2026-10-14 12:10+05:30','2026-10-14 12:55+05:30',450,'crm'),
    ('glow',null,'Tarun Goud','svc_spa',4,'2026-10-14 12:55+05:30','2026-10-14 13:55+05:30',1200,'crm'),
    ('glow',null,'Fatima Begum','svc_haircut',4,'2026-10-14 13:55+05:30','2026-10-14 14:40+05:30',450,'crm'),
    ('glow',null,'Chaitanya K','svc_beard',4,'2026-10-14 14:40+05:30','2026-10-14 15:00+05:30',200,'crm'),
    ('glow',null,'Revathi S','svc_spa',4,'2026-10-14 15:00+05:30','2026-10-14 16:00+05:30',1200,'crm'),
    ('glow',null,'Pavan Kalyan','svc_haircut',4,'2026-10-14 17:30+05:30','2026-10-14 18:15+05:30',450,'crm'),
    ('glow',null,'Hema Latha','svc_haircut',4,'2026-10-14 18:30+05:30','2026-10-14 19:15+05:30',450,'crm'),
    ('glow',null,'Siddharth M','svc_haircut',4,'2026-10-14 19:15+05:30','2026-10-14 20:00+05:30',450,'crm'),
    ('glow',null,'Uma Devi','svc_haircut',5,'2026-10-14 10:00+05:30','2026-10-14 10:45+05:30',450,'crm'),
    ('glow',null,'Zoya Ali','svc_beard',5,'2026-10-14 10:55+05:30','2026-10-14 11:15+05:30',200,'crm'),
    ('glow',null,'Bharat Kumar','svc_haircut',5,'2026-10-14 11:15+05:30','2026-10-14 12:00+05:30',450,'crm'),
    ('glow',null,'Aisha Khan','svc_haircut',5,'2026-10-14 13:00+05:30','2026-10-14 13:45+05:30',450,'crm'),
    ('glow',null,'Venkat Rao','svc_colour',5,'2026-10-14 14:00+05:30','2026-10-14 15:30+05:30',2500,'crm'),
    ('glow',null,'Divya Teja','svc_haircut',5,'2026-10-14 15:30+05:30','2026-10-14 16:15+05:30',450,'crm'),
    ('glow',null,'Rajesh Goud','svc_haircut',5,'2026-10-14 16:15+05:30','2026-10-14 17:00+05:30',450,'crm'),
    ('glow',null,'Swapna Reddy','svc_spa',5,'2026-10-14 17:00+05:30','2026-10-14 18:00+05:30',1200,'crm'),
    ('glow',null,'Manish Agarwal','svc_spa',5,'2026-10-14 18:00+05:30','2026-10-14 19:00+05:30',1200,'crm'),
    ('glow',null,'Sravani P','svc_spa',5,'2026-10-14 19:00+05:30','2026-10-14 20:00+05:30',1200,'crm'),
    ('glow',null,'Harini V','svc_haircut',6,'2026-10-14 10:00+05:30','2026-10-14 10:45+05:30',450,'crm'),
    ('glow',null,'Nitin Jain','svc_spa',6,'2026-10-14 11:00+05:30','2026-10-14 12:00+05:30',1200,'crm'),
    ('glow',null,'Asha Kiran','svc_colour',6,'2026-10-14 12:00+05:30','2026-10-14 13:30+05:30',2500,'crm'),
    ('glow',null,'Vamsi Krishna','svc_spa',6,'2026-10-14 13:30+05:30','2026-10-14 14:30+05:30',1200,'crm'),
    ('glow',null,'Lalitha Devi','svc_beard',6,'2026-10-14 15:30+05:30','2026-10-14 15:50+05:30',200,'crm'),
    ('glow',null,'Sunil Varma','svc_haircut',6,'2026-10-14 16:00+05:30','2026-10-14 16:45+05:30',450,'crm'),
    ('glow',null,'Meghana R','svc_haircut',6,'2026-10-14 16:45+05:30','2026-10-14 17:30+05:30',450,'crm'),
    ('glow',null,'Phone booking','svc_spa',6,'2026-10-14 17:30+05:30','2026-10-14 18:30+05:30',1200,'crm'),
    ('glow',null,'Phone booking','svc_haircut',6,'2026-10-14 18:30+05:30','2026-10-14 19:15+05:30',450,'crm'),
    ('glow',null,'Phone booking','svc_haircut',6,'2026-10-14 19:15+05:30','2026-10-14 20:00+05:30',450,'crm');

  perform rebuild_slots('glow', d);
  perform rebuild_slots('glow', d + 1);

  insert into demo_state (merchant_id, demo_date, clock_at, mode, scripted, sim_step, plan)
  values ('glow', d, (d + time '09:00') at time zone 'Asia/Kolkata', 'demo', false, 0, null);
end $$;

revoke all on function reset_demo() from public;
revoke all on function rebuild_slots(text, date) from public;
grant execute on function reset_demo() to anon, authenticated, service_role;
grant execute on function rebuild_slots(text, date) to service_role;

select reset_demo();
